namespace OdinInterop.Editor
{
    internal static class InteropGeneratorInbuiltFiles
    {
        internal static readonly (string, string)[] files = new (string, string)[]
        {
            ("internals.odin", INTERNALS),
        };

        private const string INTERNALS = @"// this is an autogenerated file. do not edit.
#+vet !tabs !unused !style
package src

@require import ""base:runtime""

@thread_local G_OdnTrop_Internal_Ctx: runtime.Context
@thread_local G_OdnTrop_Internal_CtxNesting: uint
";
    }
}